import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  portfolio from "../portfolio.json";
const inter = Inter({ subsets: ["latin"] });
interface Portfolio {
  title: string;
}
const portfolioData: Portfolio = portfolio.portfolio;

export const metadata: Metadata = {
  title: portfolioData.title,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
